version: 2.1
orbs:
  jira: circleci/jira@1.3.1
jobs:
  lint:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Export
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              yarn export
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              aws s3 sync out s3://sd.callisto --delete --exact-timestamps;
            fi
workflows:
  'Build and deploy to AWS S3 bucket':
    jobs:
      - build:
          post-steps:
            - jira/notify
          filters:
            branches:
              only:
                - main
      - deploy:
          post-steps:
            - jira/notify
          requires:
            - build
          filters:
            branches:
              only:
                - main
